"""empty message

Revision ID: 4372c93717ce
Revises: None
Create Date: 2016-04-18 14:25:23.255183

"""

# revision identifiers, used by Alembic.
revision = '4372c93717ce'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_annual_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('crop', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('units', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(precision=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crop_annual_production')
    ### end Alembic commands ###
